default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: davidrosillo
test:
  <<: *default
  database: davidrosillo_test

production:
  <<: *default
  database: davidrosillo_prod
