# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01467de66d6936588cb9ffaa042399ad4e8fbe6028dec6f46bb03aab51191de5ddadc9160ab0c1bd3a2126f32a98ca3e2e206cbbe6b52c4a0a9bbcecab07a12c

test:
  secret_key_base: 8e7070412bff7aba6ae8155dff70c8c477655b77e7cd4b6e11ee27ae3e05856f5a076222a869a189eebbbbe422c4eabff05abe6ff4ebe9442e3e47c1687ecbb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
